apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katib
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/katib/upstream/installs/katib-with-kubeflow
    repoURL: https://github.com/alexd2580/kubeflow-manifests.git
    targetRevision: v1.8.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
