apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvc-viewer
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/pvcviewer-controller/upstream/base
    repoURL: https://github.com/alexd2580/kubeflow-manifests.git
    targetRevision: v1.8.1
