apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubeflow-application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/alexd2580/kubeflow-manifests.git
      revision: master
      files:
      - path: "application-set/*.json"
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/alexd2580/kubeflow-manifests.git
        targetRevision: v1.8.1
        path: '{{.appPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
